export const ADD_INGREDIENT_TO_CART = "ADD_INGREDIENT_TO_CART";
export const REMOVE_INGREDIENT_FROM_CART = "REMOVE_INGREDIENT_FROM_CART";
export const ADD_BUN_TO_CART = "ADD_BUN_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const MOVE_INGREDIENT_INSIDE_CART = "MOVE_INGREDIENT_INSIDE_CART";
